version: "3.8"

services:
  app:
    container_name: ${SERVER_NAME:-mock-json-server}
    build:
      context: .
    ports:
      - ${SERVER_PORT:-3000}:3000
    environment:
      - SERVER_PORT=${SERVER_PORT:-3000}
      - SERVER_PREFIX=${SERVER_PREFIX:-v1}
    volumes:
      - ./app:/usr/local/app
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/healthcheck || exit 1
      interval: 60s
      retries: 1
      start_period: 20s
      timeout: 10s
